project_id = "sjzzbytpyinktxoddmin"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**"]

[functions.file-access]
verify_jwt = true

[functions.admin-login]
verify_jwt = false
